### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-docker-service#124]
Hey 👋 

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem! It is widely used and a huge success.

We have been looking into successful WDIO plugins like this one as we want to ensure that its development can be continued even if the original maintainer decides to move on. Therefore on behalf of the WebdriverIO community I would like to ask if you would be interested to move this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by stsvilik** [comment]
Hey Christian,

This sounds like a good idea. I’ve been trying to onboard my code onto new coding pattern you’ve been following, but didn’t have much time. I would love you to adapt my code and make it consistent with WDIO standards. I think there is room for additional features and improvements as well. On occasion I will contribute as well 😊.

What do I need to do?

Simon

From: Christian Bromann ***@***.***>
Reply-To: stsvilik/wdio-docker-service ***@***.***>
Date: Monday, June 12, 2023 at 5:52 AM
To: stsvilik/wdio-docker-service ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stsvilik/wdio-docker-service] Move project to WebdriverIO Community Org (Issue #124)


Hey 👋

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem! It is widely used and a huge success.

We have been looking into successful WDIO plugins like this one as we want to ensure that its development can be continued even if the original maintainer decides to move on. Therefore on behalf of the WebdriverIO community I would like to ask if you would be interested to move this repository into the WebdriverIO Community<https://github.com/webdriverio-community> organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by stsvilik** [comment]
Christian,

I don’t see myself in that org yet. Do I need to log-out/in to see myself there?

Simon

From: Christian Bromann ***@***.***>
Reply-To: stsvilik/wdio-docker-service ***@***.***>
Date: Tuesday, June 13, 2023 at 4:03 AM
To: stsvilik/wdio-docker-service ***@***.***>
Cc: Simon Tsvilik ***@***.***>, Comment ***@***.***>
Subject: Re: [stsvilik/wdio-docker-service] Move project to WebdriverIO Community Org (Issue #124)


Awesome, thank you so much for considering this.

What do I need to do?

Two things:

  *   I just added you to the webdriverio-community<https://github.com/webdriverio-community> org, please transfer this repository to this organisation
  *   add the NPM bot account @wdio-user<https://www.npmjs.com/~wdio-user> as maintainer to the NPM package so we can make automated releases through it

Let me know if you have any further questions.

**Comment by christian-bromann** [comment]
@stsvilik sorry, please verify now.

**Comment by stsvilik** [comment]
Christian,

I think I’m all set, let me know if I messed some of those steps up.

Simon

From: Christian Bromann ***@***.***>
Reply-To: stsvilik/wdio-docker-service ***@***.***>
Date: Tuesday, June 13, 2023 at 4:03 AM
To: stsvilik/wdio-docker-service ***@***.***>
Cc: Simon Tsvilik ***@***.***>, Comment ***@***.***>
Subject: Re: [stsvilik/wdio-docker-service] Move project to WebdriverIO Community Org (Issue #124)


Awesome, thank you so much for considering this.

What do I need to do?

Two things:

  *   I just added you to the webdriverio-community<https://github.com/webdriverio-community> org, please transfer this repository to this organisation
  *   add the NPM bot account @wdio-user<https://www.npmjs.com/~wdio-user> as maintainer to the NPM package so we can make automated releases through it

Let me know if you have any further questions.

**Comment by christian-bromann** [comment]
@stsvilik it seems that we still missing the following step:

- add the NPM bot account [@wdio-user](https://www.npmjs.com/~wdio-user) as maintainer to the NPM package so we can make automated releases through it

I wanted to update the package to work with v8 but it seems like I can't make releases. Can you check?

**Comment by dons20** [comment]
Any update on this one? I'm experiencing some issues with this service while using wdio v8, and I'm assuming it may be related.

**Comment by christian-bromann** [comment]
No updates yet, I haven't checked yet whether we have access to publish fixes to the package yet. Nor did anyone had time to work on upgrading the package in general.

**Comment by dons20** [comment]
Ok thank you. I wanted to diagnose some issues with this particular dependency while using Node v18 (the localhost ip issue is a main factor), so I just forked it and did some updates on my end to run it as a custom service, require v8 and using ESM to boot. I'm not sure if I'll get absolutely everything right with it though, but I'm down to share my progress once it isn't duplicating any existing efforts.

**Comment by christian-bromann** [comment]
@dons20 awesome, sounds great!

**Comment by dons20** [comment]
Went ahead and opened #126 as a draft. I'm sure there's lots more changes to be done if it is to be integrated but that's where I'm at for about a day or two of changes.

**Comment by christian-bromann** [comment]
@stsvilik it seems like our [WDIO Bot NPM user](https://www.npmjs.com/~wdio-user) is not listed as package maintainer with publish access. Can you help us add the bot account?

cc @dons20

**Comment by stsvilik** [comment]
What do you need me to do?

**Comment by stsvilik** [comment]
In my NPM account i do see invitation pending for this user. I re-invited today. If it still doesn't work, i can remove and re-invite.

**Comment by dons20** [comment]
@christian-bromann Could you advise here so that the bot access can be sorted out?

**Comment by dons20** [comment]
Hi all, hope you enjoyed the holiday season. Just checking in again. Is there something else that needs to be done for this issue to be resolved?
