### ISSUE TITLE
 Rename the default branch from master to main

### ISSUE THREAD

**Issue by seanpoulter** [webdriverio-community/wdio-docker-service#136]
This change would align with the other repos in webdriverio and webdriverio-community.

For more see https://github.com/github/renaming?tab=readme-ov-file#renaming-the-default-branch-from-master.

**Comment by christian-bromann** [comment]
Let's wait with this until #126 is merged.

**Comment by seanpoulter** [comment]
It's pretty easy to change the base branch:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by christian-bromann** [comment]
Updated the name. It seems that it didn't had an impact on the PR.
